@startuml

!include ./includes/authorization_elements.iuml

title Registration with AuthLS

note left of user
  Registrations happen at
  development time
end note

group Registration
  int_client->>authls: Register OIDC Client [[https://devtools.shopkeep-staging.com/internal/api-docs/identity-service/#/OIDC%20Clients%20management/post_oidc_clients swagger]]
  int_provider->>authls: Register Resource API
  legacy_idp->>authls: Register Realm [[https://devtools.shopkeep-staging.com/internal/api-docs/identity-service/#/Products%20administration/post_auth_admin_v1_products swagger]]
end

@enduml
