@startuml

!include ./includes/authorization_elements.iuml

autonumber
hide unlinked

note left of int_client: In this scenario, the Integration Client is the Product

group Logging into a product [[https://fireplace.lightspeed.app/docs-preview/62-lightspeed-id/master/20-integrating/40-unified-login-page docs]]
  note left of user
    Basic front page product login
  end note

  user->>int_client: User navigates to login page
  $applicationInitiatedLogin()
  group User has no session allowed by Integration Client (allowed_realms)
    $authentication()
  end
  authls->>int_client: Redirect to <redirect_uri>?code=<code>&state=<state>
  activate int_client
    $oidcCallback()
    alt OIDC Callback Success
      int_client->>legacy_idp: Use id_token `user` claim to assert authorization
      int_client->>int_client: Create application session
      int_client->>user: User is taken to final destination (from the `state`)
    end
    alt OIDC Callback Failure
      int_client->>user: Show error page, click here to login again [Step 1]\nImportant: set `prompt=login` in second authorization attempt
    end
    alt OIDC Callback Failure (Unified)
      int_client->>user: Redirect to [authls_domain]/unauthorized?authorization_url=...&error=<error copy>
    end
  deactivate int_client
end

@enduml
