@startuml

!include ./includes/authorization_elements.iuml

autonumber 
hide unlinked 

group Registration from another Lightspeed Product
  note left of user
    User is logged into a Lightspeed Product
  end note
  user->>int_client: Create22 account with <Integration Provider>
  $applicationInitiatedLogin()
  note over authls
    AuthLS has a session that
    the Integration Client supports
  end note
  authls->>int_client: Redirect to <redirect_uri>?code=<code>&state=<state>
  activate int_client
    $oidcCallback()
    group Create new product user and link to logged in user
      int_client->>legacy_idp: Create Product User (credentials should be null)
      int_client->>authls: Link user in AuthLS\nPOST <authls_domain>/auth/lightspeed/link { uuid, product, product_user_id }
      authls->>authls: Link new product user\nto existing user uuid
      note over authls #FFAAAA: Is this an issue?\nAuthLS session in browser\nis not aware of linked user
    end
    int_client->>int_client: Create application session
    int_client->>user: User is taken to final destination
  deactivate int_client
end
@enduml
